version: '3.9'

services:
  app:
    container_name: app_container
    build: 
      context: ../
      dockerfile: docker/Dockerfile.alpine
    environment:
      LOG_LEVEL: info
      DATABASE_URL: "postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@postgres:5432/postgres"
    volumes:
      - app_logs:/app/logs
    ports:
      - "9080:80"
    networks:
      - postgres
    depends_on:
      - postgres
      - redis
  
volumes:
  app_logs: